language: java

services:
- docker

cache:
  directories:
  - $HOME/.m2

notifications:
  email: false
  slack: bsc-projects-reveal:1EY60bGB2FgypKQkejR0B47l

jdk:
- oraclejdk8

before_install:
- npm install cesium
- mv node_modules/cesium/build src/main/resources/static/Cesium

install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

after_success:
- docker build -t vicaran/smart-ivc .
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push vicaran/smart-ivc

script:
- mvn test
