language: java

services:
- docker

cache:
  directories:
  - $HOME/.m2

notifications:
  email: false
  slack:
    rooms:
      - bsc-projects-reveal:1EY60bGB2FgypKQkejR0B47l
    on_success: never
    on_failure: always

jdk:
- oraclejdk8

before_install:
- mkdir src/main/resources/static/Cesium
- git clone https://github.com/AnalyticalGraphicsInc/cesium.git
- cd cesium
- git checkout 3d-tiles
- npm install --only=dev
- npm install
- npm run minifyRelease
- cd ../
- mv cesium/Build src/main/resources/static/Cesium/Build
- rm -Rf cesium/

install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

after_success:
- docker build -t vicaran/smart-ivc .
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push vicaran/smart-ivc

script:
- mvn test
