language: java

services:
- docker

jdk:
- oraclejdk8
# would just use default install/script but the ./mvnw script errors on travis
# obviously this only works for maven builds right now...

before_install:
- npm install cesium
- mv node_modules/cesium/Build src/main/resources/static/Cesium

install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

after_success:
- docker build vicaran/smart-ivc .
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push vicaran/smart-ivc

script:
- mvn test
